# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node.proto',
  package='ethereum.eth.v1alpha1',
  syntax='proto3',
  serialized_options=_b('\n\031org.ethereum.eth.v1alpha1B\tNodeProtoP\001Z6github.com/prysmaticlabs/ethereumapis/eth/v1alpha1;eth\252\002\025Ethereum.Eth.v1alpha1\312\002\025Ethereum\\Eth\\v1alpha1'),
  serialized_pb=_b('\n\nnode.proto\x12\x15\x65thereum.eth.v1alpha1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1d\n\nSyncStatus\x12\x0f\n\x07syncing\x18\x01 \x01(\x08\"]\n\x07Genesis\x12\x30\n\x0cgenesis_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x18\x64\x65posit_contract_address\x18\x02 \x01(\x0c\",\n\x07Version\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x10\n\x08metadata\x18\x02 \x01(\t\"\'\n\x13ImplementedServices\x12\x10\n\x08services\x18\x01 \x03(\t\"3\n\x05Peers\x12*\n\x05peers\x18\x01 \x03(\x0b\x32\x1b.ethereum.eth.v1alpha1.Peer\"P\n\x04Peer\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x37\n\tdirection\x18\x02 \x01(\x0e\x32$.ethereum.eth.v1alpha1.PeerDirection*7\n\rPeerDirection\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07INBOUND\x10\x01\x12\x0c\n\x08OUTBOUND\x10\x02\x32\xb4\x04\n\x04Node\x12n\n\rGetSyncStatus\x12\x16.google.protobuf.Empty\x1a!.ethereum.eth.v1alpha1.SyncStatus\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/eth/v1alpha1/node/syncing\x12h\n\nGetGenesis\x12\x16.google.protobuf.Empty\x1a\x1e.ethereum.eth.v1alpha1.Genesis\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/eth/v1alpha1/node/genesis\x12h\n\nGetVersion\x12\x16.google.protobuf.Empty\x1a\x1e.ethereum.eth.v1alpha1.Version\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/eth/v1alpha1/node/version\x12\x82\x01\n\x17ListImplementedServices\x12\x16.google.protobuf.Empty\x1a*.ethereum.eth.v1alpha1.ImplementedServices\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/eth/v1alpha1/node/services\x12\x63\n\tListPeers\x12\x16.google.protobuf.Empty\x1a\x1c.ethereum.eth.v1alpha1.Peers\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/eth/v1alpha1/node/peersB\x90\x01\n\x19org.ethereum.eth.v1alpha1B\tNodeProtoP\x01Z6github.com/prysmaticlabs/ethereumapis/eth/v1alpha1;eth\xaa\x02\x15\x45thereum.Eth.v1alpha1\xca\x02\x15\x45thereum\\Eth\\v1alpha1b\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_PEERDIRECTION = _descriptor.EnumDescriptor(
  name='PeerDirection',
  full_name='ethereum.eth.v1alpha1.PeerDirection',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INBOUND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTBOUND', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=477,
  serialized_end=532,
)
_sym_db.RegisterEnumDescriptor(_PEERDIRECTION)

PeerDirection = enum_type_wrapper.EnumTypeWrapper(_PEERDIRECTION)
UNKNOWN = 0
INBOUND = 1
OUTBOUND = 2



_SYNCSTATUS = _descriptor.Descriptor(
  name='SyncStatus',
  full_name='ethereum.eth.v1alpha1.SyncStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='syncing', full_name='ethereum.eth.v1alpha1.SyncStatus.syncing', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=158,
)


_GENESIS = _descriptor.Descriptor(
  name='Genesis',
  full_name='ethereum.eth.v1alpha1.Genesis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genesis_time', full_name='ethereum.eth.v1alpha1.Genesis.genesis_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit_contract_address', full_name='ethereum.eth.v1alpha1.Genesis.deposit_contract_address', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=253,
)


_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='ethereum.eth.v1alpha1.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ethereum.eth.v1alpha1.Version.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='ethereum.eth.v1alpha1.Version.metadata', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=299,
)


_IMPLEMENTEDSERVICES = _descriptor.Descriptor(
  name='ImplementedServices',
  full_name='ethereum.eth.v1alpha1.ImplementedServices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='ethereum.eth.v1alpha1.ImplementedServices.services', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=340,
)


_PEERS = _descriptor.Descriptor(
  name='Peers',
  full_name='ethereum.eth.v1alpha1.Peers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peers', full_name='ethereum.eth.v1alpha1.Peers.peers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=393,
)


_PEER = _descriptor.Descriptor(
  name='Peer',
  full_name='ethereum.eth.v1alpha1.Peer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='ethereum.eth.v1alpha1.Peer.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='ethereum.eth.v1alpha1.Peer.direction', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=475,
)

_GENESIS.fields_by_name['genesis_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PEERS.fields_by_name['peers'].message_type = _PEER
_PEER.fields_by_name['direction'].enum_type = _PEERDIRECTION
DESCRIPTOR.message_types_by_name['SyncStatus'] = _SYNCSTATUS
DESCRIPTOR.message_types_by_name['Genesis'] = _GENESIS
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['ImplementedServices'] = _IMPLEMENTEDSERVICES
DESCRIPTOR.message_types_by_name['Peers'] = _PEERS
DESCRIPTOR.message_types_by_name['Peer'] = _PEER
DESCRIPTOR.enum_types_by_name['PeerDirection'] = _PEERDIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SyncStatus = _reflection.GeneratedProtocolMessageType('SyncStatus', (_message.Message,), {
  'DESCRIPTOR' : _SYNCSTATUS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.SyncStatus)
  })
_sym_db.RegisterMessage(SyncStatus)

Genesis = _reflection.GeneratedProtocolMessageType('Genesis', (_message.Message,), {
  'DESCRIPTOR' : _GENESIS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.Genesis)
  })
_sym_db.RegisterMessage(Genesis)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.Version)
  })
_sym_db.RegisterMessage(Version)

ImplementedServices = _reflection.GeneratedProtocolMessageType('ImplementedServices', (_message.Message,), {
  'DESCRIPTOR' : _IMPLEMENTEDSERVICES,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.ImplementedServices)
  })
_sym_db.RegisterMessage(ImplementedServices)

Peers = _reflection.GeneratedProtocolMessageType('Peers', (_message.Message,), {
  'DESCRIPTOR' : _PEERS,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.Peers)
  })
_sym_db.RegisterMessage(Peers)

Peer = _reflection.GeneratedProtocolMessageType('Peer', (_message.Message,), {
  'DESCRIPTOR' : _PEER,
  '__module__' : 'node_pb2'
  # @@protoc_insertion_point(class_scope:ethereum.eth.v1alpha1.Peer)
  })
_sym_db.RegisterMessage(Peer)


DESCRIPTOR._options = None

_NODE = _descriptor.ServiceDescriptor(
  name='Node',
  full_name='ethereum.eth.v1alpha1.Node',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=535,
  serialized_end=1099,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSyncStatus',
    full_name='ethereum.eth.v1alpha1.Node.GetSyncStatus',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SYNCSTATUS,
    serialized_options=_b('\202\323\344\223\002\034\022\032/eth/v1alpha1/node/syncing'),
  ),
  _descriptor.MethodDescriptor(
    name='GetGenesis',
    full_name='ethereum.eth.v1alpha1.Node.GetGenesis',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_GENESIS,
    serialized_options=_b('\202\323\344\223\002\034\022\032/eth/v1alpha1/node/genesis'),
  ),
  _descriptor.MethodDescriptor(
    name='GetVersion',
    full_name='ethereum.eth.v1alpha1.Node.GetVersion',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_VERSION,
    serialized_options=_b('\202\323\344\223\002\034\022\032/eth/v1alpha1/node/version'),
  ),
  _descriptor.MethodDescriptor(
    name='ListImplementedServices',
    full_name='ethereum.eth.v1alpha1.Node.ListImplementedServices',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_IMPLEMENTEDSERVICES,
    serialized_options=_b('\202\323\344\223\002\035\022\033/eth/v1alpha1/node/services'),
  ),
  _descriptor.MethodDescriptor(
    name='ListPeers',
    full_name='ethereum.eth.v1alpha1.Node.ListPeers',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_PEERS,
    serialized_options=_b('\202\323\344\223\002\032\022\030/eth/v1alpha1/node/peers'),
  ),
])
_sym_db.RegisterServiceDescriptor(_NODE)

DESCRIPTOR.services_by_name['Node'] = _NODE

# @@protoc_insertion_point(module_scope)
